apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000  # This is the port your backend is running on
      targetPort: 5000  # This is the port your app exposes
      nodePort: 30001
