apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-simple-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-simple-site
  template:
    metadata:
      labels:
        app: my-simple-site
    spec:
      containers:
        - name: my-simple-site
          imagePullPolicy: Never
          image: my-simple-site:latest  # Your Docker image name
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
